INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Українська мова і література', 0);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Історія України', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Математика', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Фізика', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Хімія', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Біологія', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Географія', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Англійська мова', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Французька мова', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Німецька мова', NULL);
INSERT INTO Subjects(subject_name, adapt_scale) VALUES('Іспанська мова', NULL);